### PR TITLE
Created Dashboard for purchase order #2

### PR DESCRIPTION
**Pull request by diyah1234**

### CODE REVIEW

**Comment by Samyukta-b** [comment]
i am taking a short break, i will review this after that

**Comment by Samyukta-b** [comment]
hi, can you mention which url you want me to run to view the dashboard

**Comment by diyah1234** [comment]
I made some changes which I had missed out sorry. Please try http://127.0.0.1:8000/dashboard/ and let me know if I have to make any changes. Thank you

**Comment by Samyukta-b** [comment]
okay thanks, im going through it right now

**Comment by Samyukta-b** [comment]
it looks good! can you find a way to also display the items and price in the same display function. i've given you more 30 mins

**Comment by Samyukta-b** [comment]
@diyah1234 hi, can you give an update?

**Comment by Samyukta-b** [comment]
!bounty 350

**Comment by DedLad** [comment]
!bounty 200

**Pull request merged**
